@startuml "Test"


class Renter <<Entitiy>> {
    + name: String
    + surname: String
    + phoneNumber: String
    + mail: String
    + appointments: Appointment[]  
    + searchedHouseType: House
    + applyToRentHouse()
    + searchHouse()
    + askForAppointment()
}

class House <<Entitiy>> {
    + type: String
    + squaremeters: Number
    + numberOfRooms: Number
    + rent: Number
    + extraCosts: Number
    + floor: Number
    + basement: Boolean
    + isPetAllowed: Boolean
    + garage: Boolean
    + availableParkPlaceForHouse: Number
    + numberOfBedrooms: Number
    + numberOfBaths: Number
    + numberOfRooms: Number 
    + adress: Adress
    + description: String
    + landlord: Landlord

}
class Adress {
    + street: String
    + apartmentNumber: String
    + houseNumber: String
    + postCode: String 
}

class Landlord <<Entitiy>> {
    + name: String
    + surname: String
    + phoneNummer: String
    + mail: String
    + bewertung: Number
    + house: House
    + createAnAdvert()
    + acceptRenter()
    

}
class Appointment{
    + date: Date 
    + adress: Adress
    + renter: Renter
    + landlord: Landlord
    + accepted: Boolean
    + acceptAppointment()
    + cancelAppointment()
}



House -up-* Landlord
Adress -right-*House
Adress -up-*User


@enduml

